/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/headset.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/headset.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['gray rubber']} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['gray rubber']} position={[0.73, -0.56, -1.42]} rotation={[-0.34, 0, -2.31]} scale={0.13} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.003']} scale={0.03} />
      <group position={[2.12, -0.61, 0.03]} rotation={[1.46, 0.06, -0.39]} scale={[0.27, 0.43, 0.27]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['gray plastic matt']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.cushion.geometry} material={materials['Material.003']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.speaker.geometry} material={materials['white plastic']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.badge.geometry} material={materials['gray plastic']} rotation={[Math.PI / 2, 0, 0]} scale={0.34} />
      <mesh geometry={nodes.speaker001.geometry} material={materials['gray plastic']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.screw.geometry} material={materials['gray plastic']} scale={0.07} />
      <mesh geometry={nodes.steelfreame.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube.geometry} material={materials['white plastic']} position={[0, 0.02, 0]} scale={[1, 1, 0.1]} />
      <mesh geometry={nodes.ropes.geometry} material={nodes.ropes.material} scale={[0.08, 0.36, 0.08]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['white plastic']} scale={[0.25, 0.25, 0.06]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} scale={[0.13, 0.13, 0.03]} />
      <mesh geometry={nodes.screw2.geometry} material={materials['Material.002']} position={[-0.11, 0, 0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.BezierCurve001.geometry} material={materials['Material.003']} position={[0, 2.11, 0]} />
    </group>
  )
}

useGLTF.preload('/headset.glb')
